import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react'
import Link from 'next/link'
import { signIn, signOut, singOut, useSession } from 'next-auth/client'

export default function Home() {
  const [session, loading] = useSession()

  return (
    <div className={styles.container}>
      <Head>
        <title>NextAuth Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!session && (
          <> 
            Not Signed in
            <br/>
            <button onClick={signIn}>Sign In</button>
          </>
          )
        }
        {
          session && (
            <>
              <img src={session.user.image} /><br/>
              You are signed in as: {session.user.email} - {session.user.name}<br/>
              <div>You can now access permetioned site pages</div><br/>
              <div>
                <Link href="/secret">Visit the secret page</Link>
              </div><br/>
              <button onClick={signOut}>Sign Out</button>
              <br/>
              <div>
                {
                  JSON.stringify(session.user)
                }
              </div>
            </>
          )
        }
      </main>
    </div>
  )
}
